---
# tasks file for lighthouse
  - name: lighthouse
    git:
      repo: "{{ lighthouse_src  }}"
      version: master
      dest: "{{ lighthouse_dist  }}"
  - name: lighthouse config
    become: true
    template:
      src: lighth.conf.j2
      dest: "/etc/nginx/conf.d/default.conf"
      mode: 0644
    notify: nginx-reload
